### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by sdemura** [devopshq/teamcity#16]
objects should be able to be serialized into JSON for easier parsing/automation.

**Comment by allburov** [comment]
@sdemura 
objects can dump as python-primitives, use `to_dict` method for this:
```python
data = obj.to_dict()
# convert to JSON if needed
json.dumps(data)
```

I added this example to documentation, thanks!

**Comment by allburov** [comment]
https://devopshq.github.io/teamcity/api-usage.html#save-as-dict
