### ISSUE TITLE
Cannot install dohq_teamcity for python 2.7

### ISSUE THREAD

**Issue by 0x6C6F** [devopshq/teamcity#31]
The library seems to be incompatible with python 2.7.
In contrary to the statement in the documentation on https://devopshq.github.io/teamcity/install.html

Is this a known issue or I am doing something wrong?

![2021-02-01_19h21_17](https://user-images.githubusercontent.com/8344145/106500917-ac2d1200-64c2-11eb-9f74-ddd90fee0e01.png)

**Comment by allburov** [comment]
Hey, thanks! I've updated docs. We won't support python 2.7

**Comment by aFamilyOfTrees** [comment]
Please be sure to also update [the install page](https://devopshq.github.io/teamcity/install.html) as it still says the library is compatible with 2.7. Looks like a great library, unfortunately I'm stuck in the past :). Thanks.
