### ISSUE TITLE
builds.get_content fails with 400 error

### ISSUE THREAD

**Issue by mshinkareva** [devopshq/teamcity#42]
I've create request 
```
tc_connect = TeamCity(
            f'{settings.tc_server}',
            auth=(settings.domain_login, settings.domain_password),
       )
content = self.tc_connect.builds.get_content(
    path='/some_path/some_file.txt', build_locator='id:someid')
  
```

**Exprected result:**
Content has been got

**Actual result**
```
dohq_teamcity.rest.ApiException: (400)
Reason: 
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.21.6', 'Date': 'Wed, 12 Oct 2022 12:33:25 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Content-Length': '435', 'Connection': 'keep-alive', 'Content-Language': 'en'})
HTTP response body: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```
The next points were checked:

-  tc_connect.build_api.get_children(
    path='', build_locator='id:111') - works correctly
- I've made breakpoint in 
```
"""Makes the HTTP request using RESTClient."""
if method == "GET":
    return self.rest_client.GET(url,
                                query_params=query_params,
                                _preload_content=_preload_content,
                                _request_timeout=_request_timeout,
                                headers=headers)
```
and found that url has been changed to
```
url = 'https://teamcity-some-server.com/app/rest/builds/id%3A111/artifacts/content%2Fsome_path2Fsome_file.txt'
body = None
```
- Also I've made via raw links
`    path=r'/some_path/some_file.txt', build_locator=r'id:111'
`
- There no any user-agents in code

**Comment by Tim55667757** [comment]
@allburov or @DenKoren can you checks `get_content()` method?

Often the server requires additional headers, such as `User-agent`, it may be worth adding them to the network request.

@mshinkareva and I tried various query options and file paths, nothing worked. We only saw that the url was formed incorrectly: `https://teamcity-some-server.com/app/rest/builds/id%3A111/artifacts/content%2Fsome_path2Fsome_file.txt` in `get_content()` method.

**Comment by allburov** [comment]
Have no memory of the project :( 
Call me when PR is ready for review :)

**Comment by Tim55667757** [comment]
@antonzolotukhin Hi! Can you help to @mshinkareva ? With `get_content()` method in dohq-teamcity library?

You probably have many internal projects where this feature is involved (look at the configurations of the testers, please). Maria cannot download the file in any way because of the 400 error and a possible problem with the formation of the URL under the macos. How to run this method correctly, can you tell me?

**Comment by antonzolotukhin** [comment]
Looks like it's related to #26

**Comment by mshinkareva** [comment]
@allburov hey! Recently I made a fix https://github.com/devopshq/teamcity/commit/057d8cdc830de44dccf735f5bfb0c23df40c5bbc
but there are some problems due to travis ci credits
is it possible to merge?
